"""Blended guest scoring: the guest's own behaviour, folded in upward only

Adds the columns that hold a stay's score once the guest's own actions are taken into
account alongside the staff reviews.

`final_score` is never below the staff score: guest feedback can raise a guest's standing
and can never lower it. A complaint is the guest handing us information, and counting it
against them would punish the same act twice — once when staff rate them down, again in
the arithmetic.

`possible_retaliation` records the pattern worth a human's eye: this guest complained,
and staff scored them low.

Revision ID: 17ce50d62c3e
Revises: 0001
Create Date: 2026-09-19 18:24:23.728407
"""
from alembic import op
import sqlalchemy as sa


revision = '17ce50d62c3e'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # The NOT NULL columns carry a server_default, which autogenerate does not add.
    # Without it, ALTER TABLE fails on any table that already has rows — the migration
    # passes on an empty development database and breaks on the first real one.
    #
    # The default is then dropped: it exists to backfill the existing rows, and leaving
    # it in place would let a later insert silently skip a value the application is
    # supposed to supply.
    op.add_column(
        'stay_review_summaries',
        sa.Column('final_score', sa.Float(), nullable=True),
        schema='guest_intel',
    )
    for column, default in (
        ('engagement_bonus', '0'),
        ('guest_sentiment', '0'),
    ):
        op.add_column(
            'stay_review_summaries',
            sa.Column(column, sa.Float(), nullable=False, server_default=default),
            schema='guest_intel',
        )
        op.alter_column(
            'stay_review_summaries', column, server_default=None, schema='guest_intel'
        )

    op.add_column(
        'stay_review_summaries',
        sa.Column('possible_retaliation', sa.Boolean(), nullable=False, server_default=sa.false()),
        schema='guest_intel',
    )
    op.alter_column(
        'stay_review_summaries', 'possible_retaliation', server_default=None, schema='guest_intel'
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stay_review_summaries', 'possible_retaliation', schema='guest_intel')
    op.drop_column('stay_review_summaries', 'guest_sentiment', schema='guest_intel')
    op.drop_column('stay_review_summaries', 'engagement_bonus', schema='guest_intel')
    op.drop_column('stay_review_summaries', 'final_score', schema='guest_intel')
    # ### end Alembic commands ###
