"""Periodic work owned by inventory-service."""
import logging
from uuid import UUID
from sqlalchemy import select

from vesper_common.db import session_scope
from vesper_common.clock import utcnow
from vesper_common.scheduler import Scheduler, for_each_property

from . import service
from .models import InventoryRequest, InventoryRequestAudit, InventoryRequestLine, StockItem
from .procurement import list_requests
from app.api.identity.models import Role, User
from app.api.property.models import Department, Property

log = logging.getLogger(__name__)


def _sweep_expiring(property_id: str) -> None:
    db = session_scope()
    try:
        items = service.sweep_expiring(db, UUID(property_id))
        if items:
            log.info("%s item(s) inside the expiry window", len(items))
    finally:
        db.close()


def _recalculate_reorder(property_id: str) -> None:
    db = session_scope()
    try:
        item_ids = db.scalars(select(StockItem.id).where(
            StockItem.property_id == UUID(property_id), StockItem.is_active.is_(True))).all()
        for item_id in item_ids:
            try:
                service.maybe_flag_low(db, UUID(property_id),
                                       service.get_item(db, UUID(property_id), item_id))
            except Exception:
                db.rollback()
                log.exception("could not recalculate reorder for item %s", item_id)
    finally:
        db.close()


def _auto_replenish(property_id: str) -> None:
    """Create read-only department request cards for low stock, without approvals."""
    db = session_scope()
    try:
        prop_id = UUID(property_id)
        prop = db.get(Property, prop_id)
        if prop is None:
            return
        system_actor = db.scalars(
            select(User).join(User.role).where(
                User.property_id == prop_id, Role.key == "gm", User.is_active.is_(True)
            ).limit(1)
        ).first()
        if system_actor is None:
            log.warning("Skipping automatic stock requests for %s: no active property GM", property_id)
            return

        stock = service.list_items(db, prop_id)
        departments = db.scalars(select(Department).where(Department.property_id == prop_id)).all()
        for department in departments:
            low_items = [item for item in stock if item.department_id == department.id and item.is_low]
            if not low_items:
                continue
            existing = list_requests(db, prop_id, department_id=department.id)
            open_item_ids = {
                line.item_id for request in existing if request.status in {"submitted", "open"}
                for line in request.lines
            }
            candidates = [item for item in low_items if item.id not in open_item_ids]
            if not candidates:
                continue

            manager_id = department.head_user_id or system_actor.id
            request = InventoryRequest(
                property_id=prop_id, department_id=department.id,
                requested_by=system_actor.id, responsible_manager_id=manager_id,
                currency=prop.currency, status="submitted",
                reason="Automatic replenishment request created from current low stock.",
            )
            db.add(request)
            db.flush()
            db.add_all([
                InventoryRequestLine(
                    request_id=request.id, item_id=item.id,
                    quantity=item.reorder_quantity or item.minimum_quantity or 1,
                    unit_cost=item.unit_cost,
                    reason=f"On hand {item.quantity} {item.unit}; minimum is {item.minimum_quantity}.",
                )
                for item in candidates
            ])
            db.add(InventoryRequestAudit(
                request_id=request.id, actor_id=system_actor.id,
                action="auto_submitted", reason="Generated by the scheduled low-stock check.",
                created_at=utcnow(),
            ))
            db.commit()
            log.info("Created automatic stock request for %s (%d item(s))", department.name, len(candidates))
    except Exception:
        db.rollback()
        log.exception("Automatic low-stock request sweep failed for %s", property_id)
    finally:
        db.close()


def build() -> Scheduler:
    scheduler = Scheduler("inventory-service")
    # Expiry is a date, not a moment, so hourly is ample and keeps the badge correct
    # within an hour of midnight rolling over.
    scheduler.add("sweep-expiring-stock", 3600, for_each_property(_sweep_expiring))
    scheduler.add("recalculate-reorder", 86400, for_each_property(_recalculate_reorder))
    scheduler.add("auto-generate-low-stock-requests", 900, for_each_property(_auto_replenish))
    return scheduler
